# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_courseorg_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='全国知名', max_length=20, verbose_name='标签'),
        ),
    ]
