# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together=set([('user', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together=set([('user', 'fav_id', 'fav_type')]),
        ),
    ]
