# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_teach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teach',
            new_name='teacher',
        ),
    ]
