# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180526_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='canlearn',
            field=models.CharField(default='', max_length=300, verbose_name='课程学到什么'),
        ),
        migrations.AddField(
            model_name='course',
            name='needknown',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
