# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180526_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='courses/%Y/%m', verbose_name='封面图'),
        ),
    ]
