# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户基本信息', 'verbose_name_plural': '用户基本信息'},
        ),
    ]
